### Análise exploratória
#### Este notebook serve para explorar e sintetizar as informações dos dados coletados.

In [ ]:
""" Importação das dependências para a análise """

from src.queries import summarize, completude_dados, capitais_assiduas
import duckdb

con = duckdb.connect("dados.duckdb")

In [9]:
""" sumário da base de dados """
summarize(con).show()

┌─────────────────────┬─────────────┬──────────────────────────────────────┬─────────────────────────────────────────────┬───────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────────┬────────────────────┬───────┬─────────────────┐
│     column_name     │ column_type │                 min                  │                     max                     │ approx_unique │        avg         │        std         │        q25        │        q50        │        q75         │ count │ null_percentage │
│       varchar       │   varchar   │               varchar                │                   varchar                   │     int64     │      varchar       │      varchar       │      varchar      │      varchar      │      varchar       │ int64 │  decimal(9,2)   │
├─────────────────────┼─────────────┼──────────────────────────────────────┼─────────────────────────────────────────────┼───────────────┼────────────────────┼────────────────────┼───────────────────┼───────────────────┼────────────────────┼───────┼─────────────────┤
│ instituicao         │ VARCHAR     │ Prefeitura Municipal de Aracaju - SE │ Prefeitura Municipal do Rio de Janeiro - RJ │            24 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │            0.00 │
│ cod_ibge            │ BIGINT      │ 1100205                              │ 5208707                                     │            27 │ 2838185.543390154  │ 1155652.2385539743 │ 2081526           │ 2704302           │ 3550308            │ 50334 │            0.00 │
│ uf                  │ VARCHAR     │ AC                                   │ TO                                          │            27 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │            0.00 │
│ populacao           │ BIGINT      │ 299127                               │ 12396372                                    │           110 │ 2194815.62842214   │ 2845665.7371007665 │ 618477            │ 1151663           │ 2404814            │ 50334 │            0.00 │
│ etapa_despesa       │ VARCHAR     │ Despesas Empenhadas                  │ Inscrição de Restos a Pagar Processados     │             4 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │            0.00 │
│ conta               │ VARCHAR     │ 01 - Legislativa                     │ FU28 - Demais Subfunções                    │           178 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │            0.00 │
│ identificador_conta │ VARCHAR     │ siconfi-cor_TotalDespesas            │ siconfi-cor_TotalDespesas                   │             1 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │            0.00 │
│ valor               │ DOUBLE      │ -227951175.17                        │ 112262084025.92                             │         41049 │ 237174480.83262813 │ 1808001958.126328  │ 726475.7861404903 │ 7869833.486127795 │ 64926989.640191466 │ 50334 │            0.00 │
│ ano_exercicio       │ BIGINT      │ 2020                                 │ 2025                                        │             6 │ 2022.2777049310605 │ 1.5771111336277586 │ 2021              │ 2022              │ 2024               │ 50334 │            0.00 │
│ cod_funcao          │ VARCHAR     │ 01                                   │ 28                                          │            26 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │           14.70 │
│ nome_funcao         │ VARCHAR     │ Administração                        │ Urbanismo                                   │            30 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │           14.70 │
│ cod_subfuncao       │ VARCHAR     │ 01.031                               │ 28.846                                      │           112 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │           40.16 │
│ nome_subfuncao      │ VARCHAR     │ Abastecimento                        │ Vigilância Sanitária                        │            90 │ NULL               │ NULL               │ NULL              │ NULL              │ NULL               │ 50334 │           40.16 │
│ valor_nominal       │ DOUBLE      │ -227951175.17                        │ 112262084025.92                             │         41049 │ 237174480.83262813 │ 1808001958.126328  │ 726475.7861404903 │ 7869833.486127795 │ 64926989.640191466 │ 50334 │            0.00 │
│ valor_real          │ DOUBLE      │ -303490934.53                        │ 117049329490.63                             │         40080 │ 268384612.97437057 │ 2030368714.3395457 │ 829865.949383215  │ 9010309.808752824 │ 73890607.86732003  │ 50334 │            0.00 │
└─────────────────────┴─────────────┴──────────────────────────────────────┴─────────────────────────────────────────────┴───────────────┴────────────────────┴────────────────────┴───────────────────┴───────────────────┴────────────────────┴───────┴─────────────────┘
  15 rows                                                                                                                                                                                                                                                      12 columns

#### Completude
A completude dos dados refere-se a uma proporção de informações preenchidas de um total esperado. Abaixo está uma descrição da completude da base do finbra:

In [2]:
completude_dados(con).df()

   ano_exercicio  qtd_capitais
0           2020            26
1           2021            26
2           2022            26
3           2023            26
4           2024            26
5           2025            11

A base de dados contem os anos de 2020 há 2025, todos os anos, exceto 2025, todas as capitais declararam suas informações, com 2025 apenas 11 das 26 capitais.
15 capitais em 2025 deixaram de declarar informações financeiras.

#### Quais Capitais que entregaram em todos os anos?
A tabela abaixo mostra quais das 26 capitais declararam informações em 2025, podendo ser utilizadas para análises longitudinais apenas dessas capitais, não inviabilizando esses dados.

In [3]:
capitais_assiduas(con).df()

         municipio  uf
0       Rio Branco  AC
1           Manaus  AM
2         Salvador  BA
3        Fortaleza  CE
4          Goiânia  GO
5         São Luís  MA
6   Belo Horizonte  MG
7            Belém  PA
8   Rio de Janeiro  RJ
9      Porto Velho  RO
10   Florianópolis  SC